// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import TypeaheadController from "./typeahead_controller"
import StudyResultsController from "./study_results_controller"
import EmailMeModalController from "./email_me_modal_controller"
import ContactStudyTeamModalController from "./contact_study_team_modal_controller"
import PopoverController from "./popover_controller"
import AttributeHighlightController from "./attribute_highlight_controller"
import CampaignSourceController from "./campaign_source_controller"
import SplashRevealController from "./splash_reveal_controller"
import RecaptchaController from "./recaptcha_controller"
import SelectController from "./ts/select_controller"
import AsyncSelectController from "./ts/async_select_controller"
import { Datepicker } from "stimulus-datepicker"

application.register("typeahead", TypeaheadController)
application.register("study-results", StudyResultsController)
application.register("email-me-modal", EmailMeModalController)
application.register("contact-study-team-modal", ContactStudyTeamModalController)
application.register("popover", PopoverController)
application.register("attribute-highlight", AttributeHighlightController)
application.register("campaign-source", CampaignSourceController)
application.register("splash-reveal", SplashRevealController)
application.register("recaptcha", RecaptchaController)
application.register("ts--select", SelectController)
application.register("ts--async-select", AsyncSelectController)
application.register("datepicker", Datepicker)
